#!/bin/bash
##
## Copyright 2016 WebMarcIT Ltd
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

## These functions allow the display and modification of the classic "message of the day"
## the <base>/etc/motd file contains a running history and audit of all messages previously displayed

## The file construct
## +<date> <user> : <message>         # + Adds / changes last message
## -<date> <user> : cleared message   # - Clears last message
##
## fn_DisplayMOTD()
## fn_AdminMOTD()
## fn_EditMOTD()
# shellcheck disable=SC2154

fn_DisplayMOTD()
{
  ## Display the last line of the message of the day log file
  ## 
  local str_MOTD=
  if [ -r "${file_MOTD}" ] ; then
    str_MOTD=$(tail -1 "${file_MOTD}" | cut -d"+" -f2-)
    [ "${str_MOTD}" ] && printf "Notice %s\n" "${str_MOTD}"  && fn_ShowLine "=" || :
  fi
}
readonly -f fn_DisplayMOTD

fn_AdminMOTD()
{
  while : ; do

    ${cmd_CLEAR}

    fn_ShowTop
    printf "\n\n"
    fn_ShowLine "=" "MOTD"
    [[ -r ${file_MOTD} ]] && tail "${file_MOTD}" || :
    fn_ShowLine
    fn_DisplayMOTD
    printf "\n"
    printf "%sE%sdit | " ${dis_ULOn} ${dis_ULOff}
    printf " e%sX%sit : " ${dis_ULOn} ${dis_ULOff}

    read ${str_Quick} -t "${int_Refresh}" char_Choice

    case ${char_Choice} in
      e | e ) fn_EditMOTD  ;;
      x | X ) return 0 ;;
      *     ) return 0 ;;

    esac
  done
}

fn_EditMOTD()
{
  ## Allow authorised users to change the contents of message of the day

  local str_MOTD
  fn_CreateFile "${file_MOTD}" 2>/dev/null

  printf "\n\n Enter new message (or enter to blank out last message): \n "
  read -e str_MOTD

  if [ "${str_MOTD}" = "" ] ;then
    echo "-$(${fn_LogDate}) ${str_User}: cleared message+" >> "${file_MOTD}"
  else
    echo "+$(${fn_LogDate}) ${str_User}: ${str_MOTD}" >> "${file_MOTD}"
  fi 
}
readonly -f fn_EditMOTD
