name: Build and publish ScORCH tarball

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tarball
        run: |
          set -euo pipefail
          str_ProgramName=scorch
          str_ProgramVersion=$(grep -a "^typeset str_ProgramVersion=" ${str_ProgramName} | cut -d"=" -f2 | tr -d '"')

          tar cf scorch.tar ${str_ProgramName} bin obrar python functions plugins/DEMO
          md5sum scorch.tar > scorch.tar.md5
          sha256sum scorch.tar > scorch.tar.sha256
          cp scorch.tar        escorch.${str_ProgramVersion}.tar
          cp scorch.tar.md5    escorch.${str_ProgramVersion}.tar.md5.txt
          cp scorch.tar.sha256 escorch.${str_ProgramVersion}.tar.sha256.txt
          echo ${str_ProgramVersion} > version.txt

          mv scorch.tar        latest.tar
          mv scorch.tar.md5    latest.tar.md5
          mv scorch.tar.sha256 latest.tar.sha256
          mv bin/install       install

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
        run: |
          aws s3 cp latest.tar s3://autoscorchdownload.com/
          aws s3 cp latest.tar.md5 s3://autoscorchdownload.com/
          aws s3 cp latest.tar.sha256 s3://autoscorchdownload.com/
          aws s3 cp install s3://autoscorchdownload.com/
          aws s3 cp version.txt s3://autoscorchdownload.com/
          aws s3 cp escorch.*.tar s3://autoscorchdownload.com/
          aws s3 cp escorch.*.tar.md5.txt s3://autoscorchdownload.com/
          aws s3 cp escorch.*.tar.sha256.txt s3://autoscorchdownload.com/
